export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_MOVIE_INFO = "GET_MOVIE_INFO";
export const GET_MOVIE_CREDITS = "GET_MOVIE_CREDITS";
export const GET_SIMILAR_MOVIES = "GET_SIMILAR_MOVIES";
export const GET_MOVIE_GENRES = "GET_MOVIE_GENRES";

export const GET_TOP_RATED_TV_SHOWS = "GET_TOP_RATED_TV_SHOWS";
export const GET_TV_SHOWS_AIRING_TODAY = "GET_TV_SHOWS_AIRING_TODAY";
export const GET_POPULAR_TV_SHOWS = "GET_POPULAR_TV_SHOWS";
export const GET_TV_SHOW_INFO = "GET_TV_SHOW_INFO";
export const GET_TV_SHOW_CREDITS = "GET_TV_SHOW_CREDITS";
export const GET_SIMILAR_TV_SHOWS = "GET_SIMILAR_TV_SHOWS";
export const GET_TV_SHOW_GENRES = "GET_TV_SHOW_GENRES";

export const GET_CONFIG = "GET_CONFIG";
